<?php
/*
  File automatically modified by Blueprint.
  Editing this file might cause unexpected things to happen.
  (you've been warned)
*/

return [
  'disks' => [
    /* blueprint/disks *//* MinecraftpluginmanagerStart */ 'blueprint:minecraftpluginmanager' => [ 'driver' => 'local', 'root' => storage_path('extensions/minecraftpluginmanager'), 'url' => env('APP_URL') . '/fs/extensions/minecraftpluginmanager', 'visibility' => 'public', 'throw' => false, ], 'blueprint_private:minecraftpluginmanager' => [ 'driver' => 'local', 'root' => storage_path('.extensions/minecraftpluginmanager'), 'throw' => false, ], /* MinecraftpluginmanagerEnd *//* McmodsStart */ 'blueprint:mcmods' => [ 'driver' => 'local', 'root' => storage_path('extensions/mcmods'), 'url' => env('APP_URL') . '/fs/extensions/mcmods', 'visibility' => 'public', 'throw' => false, ], 'blueprint_private:mcmods' => [ 'driver' => 'local', 'root' => storage_path('.extensions/mcmods'), 'throw' => false, ], /* McmodsEnd *//* ModpackinstallerStart */ 'blueprint:modpackinstaller' => [ 'driver' => 'local', 'root' => storage_path('extensions/modpackinstaller'), 'url' => env('APP_URL') . '/fs/extensions/modpackinstaller', 'visibility' => 'public', 'throw' => false, ], 'blueprint_private:modpackinstaller' => [ 'driver' => 'local', 'root' => storage_path('.extensions/modpackinstaller'), 'throw' => false, ], /* ModpackinstallerEnd *//* PullfilesStart */ 'blueprint:pullfiles' => [ 'driver' => 'local', 'root' => storage_path('extensions/pullfiles'), 'url' => env('APP_URL') . '/fs/extensions/pullfiles', 'visibility' => 'public', 'throw' => false, ], 'blueprint_private:pullfiles' => [ 'driver' => 'local', 'root' => storage_path('.extensions/pullfiles'), 'throw' => false, ], /* PullfilesEnd *//* CustomserversortStart */ 'blueprint:customserversort' => [ 'driver' => 'local', 'root' => storage_path('extensions/customserversort'), 'url' => env('APP_URL') . '/fs/extensions/customserversort', 'visibility' => 'public', 'throw' => false, ], 'blueprint_private:customserversort' => [ 'driver' => 'local', 'root' => storage_path('.extensions/customserversort'), 'throw' => false, ], /* CustomserversortEnd *//* VersionchangerStart */ 'blueprint:versionchanger' => [ 'driver' => 'local', 'root' => storage_path('extensions/versionchanger'), 'url' => env('APP_URL') . '/fs/extensions/versionchanger', 'visibility' => 'public', 'throw' => false, ], 'blueprint_private:versionchanger' => [ 'driver' => 'local', 'root' => storage_path('.extensions/versionchanger'), 'throw' => false, ], /* VersionchangerEnd */
  ],
];